# Generated by Django 4.2.1 on 2023-06-16 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photography_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='date_photography',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
